#!/bin/bash

# ==============================================================================
# BYOM COMPILATION - Quantized HAR to HEF
# ==============================================================================
# This script runs INSIDE the Hailo Docker container.
# Compiles the quantized HAR generated by quantize.sh to HEF format.
#
# Usage:
#   bash compile_hef.sh <model_name> [max_utilization] [strategy] [fps]
#
# max_utilization: fraction of Hailo resources (default: 0.6)
#   0.6 - recommended (resolves PrePostAgent infeasible)
#   0.5 - more conservative, more contexts, easier mapping
#   0.8 - more aggressive, fewer contexts (may cause mapping timeout)
#
# strategy: allocation algorithm (default: greedy)
#   greedy - resolves PrePostAgent infeasible (small)
#   none   - no explicit strategy
#
# fps: target FPS (default: none = no limit)
#   30  - limits throughput optimization (resolves matmul1 on nano)
#   60  - higher target, tests if double-buffering is avoided
#   none - no FPS limit
#
# Examples:
#   bash compile_hef.sh yolo26s_seg_640
#   bash compile_hef.sh yolo26s_seg_640 0.6 greedy
#   bash compile_hef.sh yolo26n_seg_640 0.6 none 60
#   bash compile_hef.sh yolo26n_seg_640 0.6 none 30
#
# Input:  <model_name>_quantized.har
# Output: <model_name>.hef

MODEL_NAME="${1:-yolo26s_seg_416}"
MAX_UTIL="${2:-0.6}"
STRATEGY="${3:-greedy}"  # greedy or none
FPS="${4:-none}"         # number or none

DIR_BASE="/local/shared_with_docker"
QHAR="${DIR_BASE}/${MODEL_NAME}_quantized.har"
HEF="${DIR_BASE}/${MODEL_NAME}.hef"

echo "--------------------------------------------------"
echo "BYOM Compilation - HAR -> HEF"
echo "Model:           ${MODEL_NAME}"
echo "max_utilization: ${MAX_UTIL}"
echo "strategy:        ${STRATEGY}"
echo "fps:             ${FPS}"
echo "Input:           ${QHAR}"
echo "Output:          ${HEF}"
echo "--------------------------------------------------"

if [ ! -f "${QHAR}" ]; then
    echo "ERROR: Quantized HAR not found at ${QHAR}"
    exit 1
fi

python3 << PYEOF
from hailo_sdk_client import ClientRunner
import os

QHAR = "${QHAR}"
HEF  = "${HEF}"

print("Loading quantized HAR...")
runner = ClientRunner(har=QHAR)

MAX_UTIL = "${MAX_UTIL}"
STRATEGY = "${STRATEGY}"
FPS      = "${FPS}"
if STRATEGY == "none":
    alls_script = "resources_param(max_utilization=" + MAX_UTIL + ")\n"
else:
    alls_script = "resources_param(strategy=" + STRATEGY + ", max_utilization=" + MAX_UTIL + ")\n"
if FPS != "none":
    alls_script += "performance_param(fps=" + FPS + ")\n"
runner.load_model_script(alls_script)

print("Compiling to HEF (this may take several minutes)...")
hef = runner.compile()

with open(HEF, "wb") as f:
    f.write(hef)

size = os.path.getsize(HEF) / (1024*1024)
print(f"\n--------------------------------------------------")
print(f"HEF generated: {HEF} ({size:.1f} MB)")
print(f"--------------------------------------------------")
PYEOF

exit $?
