"""High-level CTE and maneuver controller for taxi robot mission integration."""

import logging

from decision.decision_fsm import State
from .robotaxi_mission import TaxiManeuver

from .parking_out_left import (
	ForcedManeuverWindow,
	ParkingOutTimer,
	ReturningProfile,
)

log = logging.getLogger("TaxiRobotCTEController")


class TaxiRobotCTEController:
	"""Owns parking-intersection CTE behavior.

	This controller handles only startup parking-out decision generated by
	ArUco 14 path split (left lane vs keep lane).
	"""

	def __init__(
		self,
		lane_offset: float = 0.80,  # lateral CTE offset magnitude during biased maneuvers
		return_duration_s: float = 1.5,  # seconds to interpolate back to lane center
	):
		# Forced windows lock the controller into a maneuver for a fixed time,
		# independent of noisy frame-by-frame detections.
		self._forced = ForcedManeuverWindow()
		# Separate timer used to detect when parking-out should end.
		self._parking_out_timer = ParkingOutTimer(duration_s=4.0)
		# Smooth interpolation profile to come back from lateral offset to center.
		self._returning = ReturningProfile(
			lane_offset=lane_offset,
			return_duration_s=return_duration_s,
		)

		self._cte_only_during_forced_states = {
			"PARKING_OUT_LEFT",
			"CROSS_LEFT",
			"CROSS_RIGHT",
		}
		# Tracks edge transitions (inactive->active or active->inactive).
		self._last_forced_active = False

	def update_startup_parking_decision(
		self,
		fsm,
		taxi_maneuver: TaxiManeuver,
	) -> None:
		# Evaluate whether a fixed forced maneuver window is currently active.
		forced_active = self._forced.is_active()

		# Startup decision only: PARKING_OUT_LEFT or PARKING_OUT_RIGHT.
		if not forced_active:
			if taxi_maneuver == TaxiManeuver.PARKING_OUT_LEFT:
				changed = fsm.signal_robotaxi_state(State.PARKING_OUT_LEFT, "Exiting parking zone: left bias")
				if changed:
					# Start fixed left-bias segment right after switching to PARKING_OUT_LEFT.
					self._forced.start("PARKING_OUT_LEFT")
			elif taxi_maneuver == TaxiManeuver.PARKING_OUT_RIGHT:
				# Keep lane on startup-right by not forcing CTE profile.
				fsm.signal_robotaxi_state(State.PARKING_OUT_RIGHT, "Exiting parking zone: right bias")

		# If a forced window just ended while still in parking-out, go back to normal.
		if (
			not forced_active
			and self._last_forced_active
			and fsm.state in (State.PARKING_OUT_LEFT, State.PARKING_OUT_RIGHT)
		):
			self._set_normal_state(fsm, "Forced parking-out completed")

		# Backup condition: parking-out cannot last forever.
		self._parking_out_timer.update(
			fsm.state in (State.PARKING_OUT_LEFT, State.PARKING_OUT_RIGHT)
		)
		if self._parking_out_timer.complete():
			self._set_normal_state(fsm, "Parking-out timeout completed")

		# Save current forced status for next-frame edge detection.
		self._last_forced_active = self._forced.is_active()

	def update_cross_left_forced_decision(
		self,
		taxi_maneuver: TaxiManeuver,
		aruco_id: int | None,
		aruco_distance_m: float | None,
	) -> None:
		"""Start a blind forced left maneuver when ArUco 13 is close enough."""
		if taxi_maneuver != TaxiManeuver.CROSS_LEFT:
			return

		if aruco_id != 13 or aruco_distance_m is None:
			return

		if aruco_distance_m <= 0.70 and not self._forced.is_active():
			self._forced.start("CROSS_LEFT", duration_s=5.0)

	def resolve_drive_state(self, fsm, env_state):
		# Drive state source is either:
		# 1) forced maneuver (hard override), or
		# 2) normal FSM process output.
		forced_active = self._forced.is_active()

		if forced_active:
			forced_state_name = self._forced.state_name()
			forced_state = getattr(State, forced_state_name, None) if forced_state_name else None
			# Fallback protects against unexpected state-name mismatches.
			current_state = forced_state if forced_state is not None else State.PARKING_OUT_LEFT
		else:
			# When not forced, let the FSM evolve naturally.
			current_state = fsm.process(
				env_state,
				planner_return_complete=self._returning.return_complete(),
			)

		# PID is reset only on forced-window edge transitions to avoid integral windup.
		pid_reset_needed = forced_active != self._last_forced_active
		self._last_forced_active = forced_active
		return current_state, pid_reset_needed

	def calculate_target_cte(self, current_state) -> float:
		# Priority 1: hard forced CTE (inside fixed maneuver windows).
		forced_cte = self._forced.forced_cte()
		if forced_cte is not None:
			self._returning.update_deviation_side(forced_cte)
			return forced_cte

		# Some maneuver states should influence CTE only during forced windows.
		if current_state.name in self._cte_only_during_forced_states:
			maneuver_cte = None
		else:
			# Priority 2: non-forced maneuver bias, if configured.
			maneuver_cte = self._forced.maneuver_cte_by_state.get(current_state.name)

		if maneuver_cte is not None:
			self._returning.update_deviation_side(maneuver_cte)
			return maneuver_cte

		# Priority 3: if returning, interpolate smoothly back to lane center.
		returning_cte = self._returning.target_cte_for_returning(
			is_returning_state=(current_state == State.RETURNING)
		)
		if returning_cte is not None:
			return returning_cte

		# Default lane-centering target.
		return 0.0

	def forced_steering_override(self) -> float | None:
		# Optional direct steering command for forced segments.
		return self._forced.steering_override()

	def reset(self) -> None:
		# Reset all maneuver and interpolation runtime state.
		self._forced.reset()
		self._parking_out_timer.reset()
		self._returning.reset()
		self._last_forced_active = False

	def _set_normal_state(self, fsm, reason: str) -> None:
		# Centralized helper: switch to normal cruise state and reset controller internals.
		if fsm.state != State.SPEED_50:
			log.info("FSM Transition: %s -> %s [%s]", fsm.state.name, State.SPEED_50.name, reason)
		fsm.state = State.SPEED_50
		self.reset()
