name: CI

on:
  push:
    branches:
      - feature/ci

jobs:
  linting-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cppcheck

      - name: Run cppcheck
        run: |
          chmod +x ./scripts/cpp_check.sh
          ./scripts/cpp_check.sh

