name: CI

on:
  push:
    branches:
      - feature/ci

jobs:
  #LINTING CHECK
  linting-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cppcheck

      - name: Run cppcheck
        run: |
          chmod +x ./scripts/ci-cd/cpp_check.sh
          ./scripts/ci-cd/cpp_check.sh

  # UNIT-TESTS
  unit-tests:
    runs-on: ubuntu-latest
    needs: linting-cpp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ git

      - name: Build and run Car Control tests
        run: |
          mkdir -p tests/car-control/build
          cd tests/car-control/build
          cmake ..
          cmake --build .
          ctest --output-on-failure

