name: CD/Cross Compile

on:
  push:
    branches:
      - feature/cd

jobs:
  cross-compile:
    runs-on: [self-hosted, Linux, X64, Docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t cross-compile .
