name: CI/Tests

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - feature/ThreadX-i2c-control

jobs:
  # UNIT TESTS
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ git

      - name: Car Control module pca9685 Unit Tests
        run: |
          sudo apt install ruby
          gem install ceedling
          cd tests/unit/Threadx_RTOS/pca9685
          ./prepare.sh
          ceedling test:all
        

  # BUILD TEST
  build:
      runs-on: [self-hosted, Linux, X64, Docker]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            lfs: true

        - name: Build Docker image
          run: |
            docker build -f docker/Dockerfile -t cross-compile .