name: CI/Tests

on:
  pull_request:
    branches:
      - develop
      - main
      
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      # -------------------------
      # Dependencies
      # -------------------------
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ git ruby dos2unix
      
      - name: Car Control Module (Unity/Ceedling)
        run: |
          cd tests/unit/ThreadX_RTOS/pca9685
          dos2unix prepare.sh
          chmod +x prepare.sh
          ./prepare.sh
          ceedling test:all
        

  # BUILD TEST
  build:
      runs-on: [self-hosted, Linux, X64, Docker]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            lfs: true

        - name: Build Docker image
          run: |
            docker build -f docker/Dockerfile -t cross-compile .
