name: CI/Tests

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - feature/ThreadX-i2c-control

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      # -------------------------
      # Dependencies
      # -------------------------
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ git ruby

      - name: Install Ceedling
        run: sudo gem install ceedling

      - name: Install QT Dependencies
        run: sudo apt install -y qt6-base-dev qt6-declarative-dev 
        run: sudo apt install libgrpc++-dev protobuf-compiler-grpc


      # -------------------------
      # UNITY (hardware tests)
      # -------------------------
      - name: Car Control Module (Unity/Ceedling)
        run: |
          cd tests/unit/ThreadX_RTOS/pca9685
          ./prepare.sh
          ceedling test:all


      # -------------------------
      # GTEST (Qt / cluster)
      # -------------------------
      - name: Build Cluster Tests (CMake + GTest)
        run: |
          cd tests/unit/car_cluster
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release 
          make -j$(nproc)

      - name: Run Cluster Tests (XML output)
        run: |
          cd tests/unit/car_cluster/build
          ./test_car_cluster --gtest_output=xml:gtest-report.xml


      # -------------------------
      # UNIFIED REPORT
      # -------------------------
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: All Unit Tests
          reporter: java-junit
          path: |
            tests/**/build/artifacts/test/*.xml
            tests/unit/car_cluster/build/gtest-report.xml
        

  # BUILD TEST
  build:
      runs-on: [self-hosted, Linux, X64, Docker]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            lfs: true

        - name: Build Docker image
          run: |
            docker build -f docker/Dockerfile -t cross-compile .